"""tender sources for multi-portal

Revision ID: 4e433dd59564
Revises: f80664eb8e68
Create Date: 2026-10-08 11:03:03.656956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e433dd59564'
down_revision: Union[str, Sequence[str], None] = 'f80664eb8e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('portal_tender_id', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('lookup_hint', sa.Text(), nullable=True),
    sa.Column('listing_hash', sa.String(length=64), nullable=False),
    sa.Column('detail_hash', sa.String(length=64), nullable=True),
    sa.Column('match_basis', sa.String(length=40), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index(op.f('ix_tender_sources_portal_id'), 'tender_sources', ['portal_id'], unique=False)
    op.create_index(op.f('ix_tender_sources_tender_id'), 'tender_sources', ['tender_id'], unique=False)
    # ### end Alembic commands ###

    # Every tender discovered before Phase 2 becomes its own PRIMARY source. Its stored hash uses the
    # old signature, so the first sighting compares field by field; identical values change nothing.
    op.execute("""
        INSERT INTO tender_sources (tender_id, portal_id, fingerprint, portal_tender_id, source_url, lookup_hint,
                                    listing_hash, detail_hash, match_basis, first_seen_at, last_seen_at)
        SELECT id, portal_id, fingerprint, portal_tender_id, source_url, NULL,
               content_hash, NULL, 'PRIMARY', first_seen_at, updated_at
        FROM tenders
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_sources_tender_id'), table_name='tender_sources')
    op.drop_index(op.f('ix_tender_sources_portal_id'), table_name='tender_sources')
    op.drop_table('tender_sources')
    # ### end Alembic commands ###
