"""bid outcomes and tender embeddings

Revision ID: 6d311f828c8c
Revises: 994d811af2ca
Create Date: 2026-10-09 01:02:03.855331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d311f828c8c'
down_revision: Union[str, Sequence[str], None] = '994d811af2ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bid_outcomes',
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('no_bid_reason', sa.String(length=40), nullable=True),
    sa.Column('our_bid_value_inr', sa.BigInteger(), nullable=True),
    sa.Column('award_value_inr', sa.BigInteger(), nullable=True),
    sa.Column('winner', sa.String(length=300), nullable=True),
    sa.Column('our_rank', sa.Integer(), nullable=True),
    sa.Column('loss_reason', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tender_id')
    )
    op.create_index(op.f('ix_bid_outcomes_stage'), 'bid_outcomes', ['stage'], unique=False)
    op.create_table('tender_embeddings',
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tender_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tender_embeddings')
    op.drop_index(op.f('ix_bid_outcomes_stage'), table_name='bid_outcomes')
    op.drop_table('bid_outcomes')
    # ### end Alembic commands ###
