"""initial schema

Revision ID: f80664eb8e68
Revises: 
Create Date: 2026-10-08 02:10:29.736734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f80664eb8e68'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capabilities',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category_code', sa.String(length=5), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('offering', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('portals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('connector', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('acquisition_method', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_minutes', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=30), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('blocker', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=40), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_claim', 'processing_jobs', ['status', 'run_after'], unique=False)
    op.create_index('ix_jobs_dedupe', 'processing_jobs', ['dedupe_key', 'status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('capability_synonyms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.String(length=60), nullable=False),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('match_type', sa.String(length=10), nullable=False),
    sa.Column('sub_capability', sa.String(length=200), nullable=True),
    sa.Column('case_sensitive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_synonyms_capability_id'), 'capability_synonyms', ['capability_id'], unique=False)
    op.create_table('portal_credentials_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('auth_type', sa.String(length=30), nullable=False),
    sa.Column('username_env_var', sa.String(length=100), nullable=True),
    sa.Column('secret_env_var', sa.String(length=100), nullable=True),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('authorized_by', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('oem_id', sa.Integer(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['oem_id'], ['oems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('portal_tender_id', sa.String(length=200), nullable=True),
    sa.Column('reference_number', sa.String(length=300), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('organization', sa.String(length=500), nullable=True),
    sa.Column('department', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('tender_type', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tender_value_inr', sa.BigInteger(), nullable=True),
    sa.Column('emd_inr', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('corrigendum', sa.Text(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('pipeline_status', sa.String(length=30), nullable=False),
    sa.Column('documents_status', sa.String(length=40), nullable=False),
    sa.Column('blocker_note', sa.Text(), nullable=True),
    sa.Column('analysis_mode', sa.String(length=20), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('opportunity_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('match_confidence', sa.Integer(), nullable=True),
    sa.Column('primary_capability', sa.String(length=200), nullable=True),
    sa.Column('matched_capabilities', sa.JSON(), nullable=False),
    sa.Column('matched_products', sa.JSON(), nullable=False),
    sa.Column('service_value_inr', sa.BigInteger(), nullable=True),
    sa.Column('product_value_inr', sa.BigInteger(), nullable=True),
    sa.Column('value_analysis', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('relevance_reason', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('extracted', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['portal_id'], ['portals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fingerprint')
    )
    op.create_index(op.f('ix_tenders_closing_at'), 'tenders', ['closing_at'], unique=False)
    op.create_index(op.f('ix_tenders_decision'), 'tenders', ['decision'], unique=False)
    op.create_index(op.f('ix_tenders_opportunity_type'), 'tenders', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_tenders_pipeline_status'), 'tenders', ['pipeline_status'], unique=False)
    op.create_index(op.f('ix_tenders_portal_tender_id'), 'tenders', ['portal_tender_id'], unique=False)
    op.create_index(op.f('ix_tenders_priority'), 'tenders', ['priority'], unique=False)
    op.create_index(op.f('ix_tenders_score'), 'tenders', ['score'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=True),
    sa.Column('tender_version', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('recipients', sa.JSON(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index(op.f('ix_alerts_tender_id'), 'alerts', ['tender_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tender_id'), 'audit_logs', ['tender_id'], unique=False)
    op.create_table('extracted_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('tender_version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('component_kind', sa.String(length=20), nullable=True),
    sa.Column('value_inr', sa.BigInteger(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_requirements_tender_id'), 'extracted_requirements', ['tender_id'], unique=False)
    op.create_table('manual_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('tender_version', sa.Integer(), nullable=False),
    sa.Column('reason_code', sa.String(length=60), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_reviews_tender_id'), 'manual_reviews', ['tender_id'], unique=False)
    op.create_table('rejection_reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('tender_version', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rejection_reasons_tender_id'), 'rejection_reasons', ['tender_id'], unique=False)
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('tender_version', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_tender_id'), 'scores', ['tender_id'], unique=False)
    op.create_table('tender_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('extraction_method', sa.String(length=30), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_documents_sha256'), 'tender_documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_tender_documents_tender_id'), 'tender_documents', ['tender_id'], unique=False)
    op.create_table('tender_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('tender_version', sa.Integer(), nullable=False),
    sa.Column('capability_id', sa.String(length=60), nullable=False),
    sa.Column('capability_name', sa.String(length=200), nullable=False),
    sa.Column('sub_capability', sa.String(length=200), nullable=True),
    sa.Column('product_ids', sa.JSON(), nullable=False),
    sa.Column('explicit_oem', sa.Boolean(), nullable=False),
    sa.Column('match_type', sa.String(length=10), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_matches_tender_id'), 'tender_matches', ['tender_id'], unique=False)
    op.create_table('tender_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id', 'version')
    )
    op.create_index(op.f('ix_tender_versions_tender_id'), 'tender_versions', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_versions_tender_id'), table_name='tender_versions')
    op.drop_table('tender_versions')
    op.drop_index(op.f('ix_tender_matches_tender_id'), table_name='tender_matches')
    op.drop_table('tender_matches')
    op.drop_index(op.f('ix_tender_documents_tender_id'), table_name='tender_documents')
    op.drop_index(op.f('ix_tender_documents_sha256'), table_name='tender_documents')
    op.drop_table('tender_documents')
    op.drop_index(op.f('ix_scores_tender_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_rejection_reasons_tender_id'), table_name='rejection_reasons')
    op.drop_table('rejection_reasons')
    op.drop_index(op.f('ix_manual_reviews_tender_id'), table_name='manual_reviews')
    op.drop_table('manual_reviews')
    op.drop_index(op.f('ix_extracted_requirements_tender_id'), table_name='extracted_requirements')
    op.drop_table('extracted_requirements')
    op.drop_index(op.f('ix_audit_logs_tender_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_alerts_tender_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_tenders_score'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_priority'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_portal_tender_id'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_pipeline_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_opportunity_type'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_decision'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_closing_at'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_table('products')
    op.drop_table('portal_credentials_metadata')
    op.drop_index(op.f('ix_capability_synonyms_capability_id'), table_name='capability_synonyms')
    op.drop_table('capability_synonyms')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_jobs_dedupe', table_name='processing_jobs')
    op.drop_index('ix_jobs_claim', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_table('portals')
    op.drop_table('oems')
    op.drop_table('capabilities')
    # ### end Alembic commands ###
